# Generated by Django 5.1.7 on 2025-03-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload_Data',
            new_name='Upload',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
